file(TO_NATIVE_PATH "${GIT_WORKING_DIRECTORY}" GIT_WORKING_DIRECTORY)
file(TO_NATIVE_PATH "${GIT_APPLY_PATCH_PATH}" GIT_APPLY_PATCH_PATH)
message(STATUS "Apply '${GIT_APPLY_PATCH_PATH}' at '${GIT_WORKING_DIRECTORY}'")

execute_process(
    COMMAND git apply ${GIT_APPLY_PATCH_PATH}
    WORKING_DIRECTORY ${GIT_WORKING_DIRECTORY}
)
